### ISSUE TITLE
Points Table issue

### ISSUE THREAD

**Issue by OB1TO-Senp1e** [CCXLV/pubgm-st-react-hud#2]
The points table doesn't change with the increment or decrement of the number in the control section

**Comment by CCXLV** [comment]
Sorry for the late response! Just to clarify, are you referring to when you add points manually, and they only update the total points but not the elimination points? Let me know if that’s what you meant.

**Comment by OB1TO-Senp1e** [comment]
Yess yess

**Comment by OB1TO-Senp1e** [comment]
Its not getting updated on the Control panel the digit "0" doesn't change
with - and +

**Comment by CCXLV** [comment]
The "0" in the Control panel shouldn't be changed while incrementing or decrementing the points. The "0" can be changed to any number by just clicking on it and after you type a number and press enter the number will be added to the total points of the team. It only adds the number to total points and not elimination points so, I could make it so it will add to both if that's better.

**Comment by CCXLV** [comment]
It's a feature of manually typing a number to add some points, it works even with negative numbers, the thing is it doesn't affect the elimination points on the Table

**Comment by CCXLV** [comment]
Hi @OB1TO-Senp1e , I have made some updates and fixes in the latest commit: [5413133
](https://github.com/CCXLV/pubgm-st-react-hud/commit/541313373cc25248b97fd9cdf731ee7c6eba761b)

In particular now manually typed points does affect the team's eliminations and also there was error regarding teams background color while they were being eliminated, which was also fixed. I am gonna close this issue now, feel free to open anytime!
